# Generated by Django 5.2.6 on 2025-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance')], max_length=100),
        ),
    ]
