# Generated by Django 5.2.6 on 2025-11-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance')], max_length=100, null=True),
        ),
    ]
