# Generated by Django 5.2.6 on 2025-11-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sequence_number',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
