# Generated by Django 5.2.6 on 2025-11-30 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_sequence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='sequence_number',
        ),
        migrations.AddField(
            model_name='lesson',
            name='indentation',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
