# Generated by Django 5.2.6 on 2025-11-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['indentation']},
        ),
    ]
