# Generated by Django 5.2.6 on 2025-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
