# Generated by Django 5.2.6 on 2025-11-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_lesson_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
    ]
